name = "TerminalCalendar"
uuid = "9e34d9e9-352a-4bdb-89aa-065cccceaa64"
authors = ["Dimitar Vanguelov <dvanguelov@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
PrettyTables = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
